name = "cyyinfo-api-test"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_EXPIRE_HOURS = "72"

[[d1_databases]]
binding = "DB"
database_name = "cyyinfo-db"
database_id = "c8f4912f-bf69-4aca-8ff4-c266649799bc"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "cyyinfo-uploads"
