name = "cyyinfo-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_EXPIRE_HOURS = "72"

[[ratelimits]]
name = "LOGIN_RATE_LIMITER"
namespace_id = "1001"
[ratelimits.simple]
limit = 5
period = 60

[[ratelimits]]
name = "REGISTER_RATE_LIMITER"
namespace_id = "1002"
[ratelimits.simple]
limit = 30
period = 60

[[ratelimits]]
name = "PASSCODE_RATE_LIMITER"
namespace_id = "1003"
[ratelimits.simple]
limit = 5
period = 60

[[ratelimits]]
name = "MESSAGE_RATE_LIMITER"
namespace_id = "1004"
[ratelimits.simple]
limit = 10
period = 60

[[d1_databases]]
binding = "DB"
database_name = "cyyinfo-db"
database_id = "c8f4912f-bf69-4aca-8ff4-c266649799bc"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "cyyinfo-uploads"
